#include "ir.h"

/*
ADC_init
Initializes the information used by the ADC
Inputs: None
Outputs: None
Side Effects: Changes ADC registers.
*/
void ADC_init() {
    // Enable conversion of the control register
    // Lecture slides give the commented out line, but it does not make 
    // sense when referring to documentation
    // ADC14 -> CTL0 = 0x00000010;
    ADC14 -> CTL0 &= ~0x00000010;
    /*
    Sample-and-hold pulse mode select: SAMPCON signal sourced from the 
    sampling timer 
    SHP = 1 
    Clock source select: SYSCLK 
    SSELx = 001 
    Number of ADC14CLK cycles in the sampling period for registers ADC14MEM0 
    to ADC14MEM7 and ADC14MEM24 to ADC14MEM31: 32 
    SHT0x = 0011 
    */
    ADC14 -> CTL0 |= 0x04080300;
    /*
    ADCRES = 10 12-bit resolution (14 clock cycle conversion time) 
    */
    ADC14 -> CTL1 = 0x00000020;
    /*
    Reserved = 0 (16 bits) 
    Window comparator threshold register selection 
    WINCTH = 0 
    Comparator window enable
    WINC = 0 
    Differential mode 
    DIF = 0 
    Reserved = 0 
    Selects combinations of V(R+) and V(R-) sources as well as the buffer 
    selection and buffer on or off. V(R+) = AVCC, V(R-) = AVSS
    VRSEL = 0000 
    End of sequence: Not end of sequence
    EOS = 0 
    Reserved = 00
    Input channel select: If ADC14DIF = 0, A6 
    INCHx = 00110
    */
    ADC14 -> MCTL[5] = 0x06;

    // A6 associated Pin
    P4SEL1 |= BIT7;
    P4SEL0 |= BIT7;

    ADC14 -> CTL1 |= 0x00050000;
    ADC14 -> CTL0 |= 0x02; // Enable ADC
}

/*
read_ADC
Reads the value generated by the ADC
Inputs: None
Outputs: 16 bit unsigned generated by ADC
Side Effects: None
*/
uint16_t read_ADC() {
    uint16_t adc_val;
    // Wait for flag to be set
    while (!ADC14->IFGR0);
    adc_val = (uint16_t) (ADC14 -> MEM[5] & 0x0000FFFF);
    return adc_val;
}

/*
set_adcval
Sets the ADC value
Inputs: Value to set ADC
Outputs: None
Side Effects: Modifies ADC value global
*/
void set_adcval(uint16_t val) {
    adcval = val;
}
